### ISSUE TITLE
运行时报错 [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by shy123123** [jdh-algo/JoyHallo#17]
根据markdown指引运行项目时，产生错误，不知道该如何解决

  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\subprocess.py", line 973, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\subprocess.py", line 1469, in _execute_child
    raise(e)
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\subprocess.py", line 1459, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[2024-10-30 18:11:50,939] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5916) of binary: C:\Users\alex\.conda\envs\joyhallo-1\python.exe
Traceback (most recent call last):
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\alex\.conda\envs\JoyHallo-1\Scripts\accelerate.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\site-packages\accelerate\commands\accelerate_cli.py", line 46, in main
    args.func(args)
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\site-packages\accelerate\commands\launch.py", line 1042, in launch_command
    deepspeed_launcher(args)
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\site-packages\accelerate\commands\launch.py", line 754, in deepspeed_launcher
    distrib_run.run(args)
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\site-packages\torch\distributed\run.py", line 803, in run
    elastic_launch(
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\site-packages\torch\distributed\launcher\api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\alex\.conda\envs\joyhallo-1\lib\site-packages\torch\distributed\launcher\api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
scripts.inference FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-30_18:11:50
  host      : DESKTOP-V28UFFB
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5916)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by DBDXSS** [comment]
看起来是torch deepspeed accelerate中的一个出问题了，可以尝试重新安装这些修复一下，如果还不行可以列一下你的系统配置和更详细的输出日志
