### ISSUE TITLE
KeyError: 'embedding'

### ISSUE THREAD

**Issue by O-O1024** [jdh-algo/JoyHallo#5]
`python scripts/app.py`

```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "/root/JoyHallo/scripts/app.py", line 693, in predict
    return inference(cfg, image_processor, audio_processor, pipeline, audioproj, save_dir, global_step, clip_length)
  File "/root/JoyHallo/scripts/app.py", line 321, in inference
    source_image_lip_mask = image_processor.preprocess(
  File "/root/JoyHallo/scripts/../joyhallo/datasets/image_processor.py", line 137, in preprocess
    face_emb = face["embedding"]
KeyError: 'embedding'
```

**Comment by O-O1024** [comment]
pretrained_models/face_analysis/ 缺少模型
